### ISSUE TITLE
`<script>` tag parsing fail with extra linefeed

### ISSUE THREAD

**Issue by DavidPeicho** [pngwn/MDsveX#11]
Hi,

There is a little parsing error when adding empty lines into a `<script>` tag:

For instance, this **will** compile:
```javascript
<style>
  .nonono {
    color: white;
  }
</style>
```

And this **will not** compile:
```javascript
<style>

  .nonono {
    color: white;
  }

</style>
```
In the second case it looks like MarkdownIT will try to parse it, because the output is something like:

```html
<style>
  <p>.nonono {
  color: white;
}</p></style>
```

**Comment by pngwn** [comment]
This is a different issue to #10 but a similar solution will fix it. The issue here is standard markdown rules:  double line breaks are always a new paragraph unless some other matching syntax appears (like a markdown block or HTML tag) and this is even true inside of an HTML block. Since CSS syntax isn't recognised by the markdown parser, weirdness ensues.

The solution mentioned in #10 would fix this, and completely remove the need for any special handling of `<style>` tags.

**Comment by pngwn** [comment]
Also fixed in the latest version.
