### ISSUE TITLE
MDsveX + Katex

### ISSUE THREAD

**Issue by cesutherland** [pngwn/MDsveX#113]
Awesome project!  I've been impressed by the expressiveness of Svelte's reactive-ness, and you've got a beautiful repl here.

I'd like to report an issure regarding integration with [katex](https://katex.org/), where `<` signs result in a `Expected valid tag name` error.  Katex is correctly transformed.  This is related to or the same root cause as #76 .

I have [a tidy little test case here](https://github.com/cesutherland/test-cases/tree/master/mdsvex/katex).

svelte config:

```js
  svelte({
    extensions: [".svelte", ".svx"],
    preprocess: mdsvex({
      remarkPlugins: [
        remarkMath,
      ],
      rehypePlugins: [
        [rehypeKatex, {output: 'html'}],
      ],
    })
  })
```

svx input:

```latex
# Header

Some text.

## Header 2

A function:

$$
f(x) = \sum_{n=0}^{\infty}a^ncos(b^n \pi x)
$$

where $$0 < a < 1$$, $$b$$ is a positive odd integer, and $$ab > 1 + \frac{3}{2}\pi$$.
```

error:
```
[!] (plugin svelte) ParseError: Expected valid tag name
test.svx
59: ></span><span
60:   class="mrel"
61: ><</span><span
      ^
62:   class="mspace"
63:   style="margin-right:0.2777777777777778em;"
```

**Comment by pngwn** [comment]
Yeah, this is indeed the same issue as #76. Appreciate the test case!

I do have a fix for this but it is a little involved. I have something in the works that will address a number of formatting/ encoding issues as well as a host of other benefits but it is quite foundational and will take some time given my limited schedule.

**Comment by cesutherland** [comment]
@pngwn appreciate it!  I'll keep my eye out.

**Comment by pngwn** [comment]
[This comment](https://github.com/pngwn/MDsveX/issues/76#issuecomment-674267071) pretty much covers this issue as well. With one difference, this case should be easier to optimise since it uses custom syntax, there is at least the possibility of escaping the conflicting characters automatically. This doesn't depend on precisely how the plugin itself generates it's output but possible is better than nothing. :D

I am going to close this issue and keep the older one open to keep track. I'll reference this from that issue.
