### ISSUE TITLE
Rendering raw MDX content

### ISSUE THREAD

**Issue by jervtub** [pngwn/MDsveX#115]
Hi,

I got a question about rendering raw MDX. How to render when I have the MDX in raw text format as below?

Consider the MDX file
``` MDX
---
title: "test"
---
# {test}
Test text
```

This content is passed as a string to the `MDX`-parameter of the `Post.svx`-component
```Svelte
<script>
  export let MDX;
</script>
{MDX}
```
The above won't render the mdx, rather it is displayed in it's raw form encapsulated within a `<p>`.

**Comment by pngwn** [comment]
Passing strings around won't work because mdsvex operates at compile time, props operate at runtime. You have a few options.

You can import the file and use it as a component:

```svelte
<script>
  import MDsveX from './MDsveX.svx';
</script>

<MDsveX />
```

If you want to pass the mdsvex file via a parent that is invoking `Post.svx` then use slots:
```svelte
<!-- Post.svx -->

<slot />
```

```svelte
<!-- something that is calling Post.svx -->

<script>
  import Post from './Post.svx';
  import MDsveX from './MDsveX.svx'; 
</script>

<Post>
  <MDsveX />
</Post>
```

The only way passing it via a prop could work is if you compile and render the mdsvex component to a plain html string, then you could use `{@html mdsvex}` to render that HTML.

**Comment by jervtub** [comment]
I want to dynamically import `.svx`-files stored under a directory `./content`.
Importing and rendering as outlined below is sufficient for what I seek:
``` Svelte
<script>
// ...
export let files;
let components = {};
files.forEach( file => 
  import( `./content/${file}.svx` ).then( MDXcomponent => 
    components[ file ] = MDXcomponent.default;
  );
</script>

<svelte:component this={components[ target ] } />
```

Just one problem remaining. An import with a fixed string, such as `import( "./content/Document.svx" )` is somewhere in the compilation process resolved to a generated component name, such as `import('./Document.cb67bea1.js')`, however if instead a variable is used, such as `import( './content/' + file )`, there isn't any resolution and therefore the component is not found...

**Comment by pngwn** [comment]
That is because rollup or webpack cannot determine all of the modules that the dynamic import could refer to (`file` is only available at runtime and could be anything at all). You would need to manually generate the `files` and make the dynamic path relative to the root of your online folder structure.

For example, `"./content/" + file` could refer to `"./content/somefile.js"` but it if `file` was equal to `"some/path/to/a/module.js"` then the source of that module would be drastically different. You need to get all of the values that `file` could be and compile/bundle them if necessary and make them accessible at runtime, because rollup will not bundle them for you if the import path is dynamic.

So if `file` could be one of 10 different files. Put those files in a folder that makes them accessible at `example.com/content/[file].js` and your dynamic import should work fine.
