### ISSUE TITLE
Importing a .svx file in another .svx file overwrites frontmatter data

### ISSUE THREAD

**Issue by aabounegm** [pngwn/MDsveX#130]
I am trying to use one `.svx` page as a component in another one, but then the frontmatter data defined in the imported one (even if it doesn't have any) removes any frontmatter data defined in the page that imports it. What should I do to properly import a `svx` file in another?

Using **Sapper** _v0.28.0_, **MDsveX** _v0.8.6_, **Svelte** _v3.24_, and **Rollup** _v2.18.2_

**Comment by pngwn** [comment]
Oh that is interesting, i'll take a look at this.

**Comment by aabounegm** [comment]
Any updates on this?
I have a feeling that the culprit is [this line](https://github.com/pngwn/MDsveX/blob/master/packages/mdsvex/src/transformers/index.ts#L56), but I didn't test anything so I'm not sure.

**Comment by pngwn** [comment]
Do you have a simple reproduction? If not I'll take a look at this later today.

**Comment by aabounegm** [comment]
If you have no problem cloning my repo and running it locally, check out https://github.com/illright/attractions
It is not so simple, but you only need to look at 2 files: [CHANGELOG.md](https://github.com/illright/attractions/blob/develop/CHANGELOG.md) and [docs/src/routes/docs/changelog.svx](https://github.com/illright/attractions/blob/develop/docs/src/routes/docs/changelog.svx) (as I write this now, I realize I forgot to remove the frontmatter from the `svx` file, but you can play around with it). Just try the combinations of having it in either file and check the tab title of the changelog page. If you remove the frontmatter from the first file (the `md` one), you should see `undefined` in the tab title.
To run it, just run `yarn` followed by `yarn docs:dev` in the root folder.

If it feels like too much work, I would gladly create a simpler reproduction, but not before the weekend :)

**Comment by pngwn** [comment]
The frontmatter isn't being wiped out by mdsvex here, you are setting the `head` of the document twice. You are wrapping both the `md` files and the `svx` files in the same layout and that layout is setting the head contents but it doesn't always have the correct props to do this. That means you effectively have two components trying to set the head, both the `svx` file _and the `md` file. In svelte whichever component is deeper in the tree will apply the head contents last and that will be what ends up in the head.

You are essentially doing this:

```svelte
<Layout {...frontmatter}>

  <Layout {...frontmatter}>
    <Changelog />
  </Layout>

</Layout>
```

The issue with `undefined` is that if you invoke a layout and it is expecting props you _have_ to pass those props if you are going to use them. In this case not providing a `name` as frontmatter causes the head title to be set to undefined because `name` is not being passed in, using a value that isn't passed down in Svelte will default to undefined, which will then get stringified.

This is what your `md` and `svx` components actually compile to if you don't have any frontmatter in the `changelog.md`:

```svelte
<!-- changelog.md -->
<script>
  import Layout from './x.svelte';
</script>

<!-- there is no front matter so there are no props, when this layout tries to set the head to `name` it is undefined. -->
<!-- this layout is applied last so whatever you set in the head here will be what is on the page -->
<Layout> 
  <!-- content here -->
</Layout>
```

```svelte
<!--  changelog.svx -->
<script>
  import Changelog from './y.svelte';

  const name = 'CHANGELOG';
</script>

<!-- `name` is passed down here and svelte correctly uses it to set the head -->

<Layout {name} > 
  <Changelog /> <!-- however this head setting is immediately overwritten by this component's layout -->
</Layout>
```

To fix this switch off layouts for the `md` file (if you want to set frontmatter in the `svx` file), you can disable layouts on a per file basis by setting the following frontmatter:
```md
---
layout: false
---
```

If you want to do this the other way around, and respect the `md` files frontmatter then switch it around and disable layouts for the `svx` file. 

You can also make use of the 'auto-layout' feature which will try to map layouts to file paths. Since the `svx` file is in a `docs` folder and the `changelog.md` isn't you can set layout to an object like so:

```js
layout: {
  docs: './src/mdsvex/layout.svelte'
}
```

This will apply the provided layout to any file with has `docs` in it's path (which, in this case, means your svx file but not your md file). I've tested this with your app and this seems to work fine in this case.

I hope this helps!

**Comment by aabounegm** [comment]
Wow, that was extremely helpful. Thanks for taking the time and effort to explain all of this!
I tried to go with the last of the options you mentioned since it's the most relevant (as having `layout: false` in the `md` file defeats the purpose of wanting to remove the frontmatter from it, and adding `layout: docs` in all other files is not really feasible), but it didn't work. All I did was remove the frontmatter from `CHANGELOG.md` and make the layout option an object exactly as you suggested:
```js
layout: {
  docs: './src/mdsvex/layout.svelte'
}
```
but then it doesn't get applied anywhere, except if I explicitly specify `layout: docs` in the frontmatter of the `svx` files. I tried other options for the layout name (like `src`, `routes`, `components`, ...), but they all only work if I explicitly specify the layout in the `svx` and not through the folder name. Is this exactly how you tested it?
Again, I'm very grateful for your dedication to trying it on my app 😄

**Comment by pngwn** [comment]
Interesting, I just pulled down your changes and tested it and it works fine for me. Did you make sure to clear any caches, etc?

It may be a bug with my path matching. What operating system are you on? Could you `console.log(__dirname)` in the rollup config and rerun the build and tell me what the output is?

**Comment by aabounegm** [comment]
Yes, I tried it in incognito to make sure nothing is cached, and even selected the "disable cache" option in Chrome DevTools
I'm on Windows 10 (version 2004, build 19041.450). `__dirname` in rollup's config prints `D:\Projects\attractions\docs`

**Comment by pngwn** [comment]
Could yopu go into `node_modules/mdsvex/dist/main.cjs.js` and go to line `25397` this should be inside a function called `map_layout_to_path` replace the whole of line `25397` (which should start with `new RegExp...`) with the following and see if this works.

```js
new RegExp(`\\` + `${path.sep}${l}` + `\\` + `${path.sep}`).test(path.normalize(filename).replace(process.cwd(), ''))
```

**Comment by aabounegm** [comment]
Yes it does!

**Comment by pngwn** [comment]
Perfect, the problem was different path separators on windows and *nix (a problem i have faced before), i'll fix this and publish a new version shortly.

**Comment by pngwn** [comment]
I have just published a new version with this fix, if you could check it out to make sure it works I would appreciate it!

**Comment by aabounegm** [comment]
Yes, that fixed it! Thank you very much. Your help and response time is highly appreciated! 😄
