### ISSUE TITLE
Commented line inside fenced code block causing problems

### ISSUE THREAD

**Issue by josefaidt** [pngwn/MDsveX#142]
## Description

I have a fenced code block that looks like this

```js
// express-fs-router/index.js
switch (typeof handler) {
  case 'function': {
    // export default function(req, res) {}
  }
  case 'object': {
    if (Array.isArray(handler) && handler.length) {
      // export default [function(req, res, next) {}, function(req, res) {}]
    }
  }
}
```

which is ultimately rendered as 

![image](https://user-images.githubusercontent.com/5033303/92795875-566e9680-f376-11ea-8f95-d19650172511.png)

Later in the same file I have a _very_ similar fenced code block that does not cause a similar issue

```js
// express-fs-router/index.js
switch (typeof handler) {
  case 'function': {
    // export default function(req, res) {}
  }
  case 'object': {
    if (Array.isArray(handler) && handler.length) {
      // export default [function(req, res, next) {}, function(req, res) {}]
      // get HTTP method from handler function name
      if (!method) method = handler[handler.length - 1].name
      // set to router
      router[method](route, ...handler)
    }
  }
}
```

which renders as

![image](https://user-images.githubusercontent.com/5033303/92796033-7900af80-f376-11ea-9b8c-70b5049691ff.png)

**Comment by pngwn** [comment]
I can't even begin to understand why this might be happening. I'm going to need a reproduction of this if that is possible.

**Comment by josefaidt** [comment]
@pngwn thanks for the swift response, I would assume because it's the first mention of `export default function () {}` perhaps it's being parsed as a module? That would explain why it shows up on the first instance but not the second.

Repo: https://github.com/josefaidt/josef.dev
File shown above: https://github.com/josefaidt/josef.dev/blob/main/pages/posts/2020/06/new-express-fs-router-features/index.svx

**Comment by pngwn** [comment]
I actually have an idea about why this may be happening, even though it is odd. 

Thanks for the repro, I'll dig into this a bit more after work!

**Comment by pngwn** [comment]
Okay, my suspicions have been confirmed.

The hot module reloading functionality in `svelte-loader` is doing this. You can see the logic on [this line](https://github.com/sveltejs/svelte-loader/blob/master/index.js#L28-L50). It is injecting this code whenever the regex matches. The reaosn it only happens once is because it isn't a global `string.replace` call so it only injects once. 

I can't really do anything in mdsvex to fix this as far as I'm aware, I think this would need to be dealt with in the loader itself. The offending string is `export default`, if it were a plain `function` it would not happen.

Not sure how to proceed with this one. I think a simple repro and an issue on the `svelte-loader` repo might be in order.

**Comment by josefaidt** [comment]
Thank you @pngwn I've opened an issue with `svelte-loader`!

**Comment by ekhaled** [comment]
Please check that you have done this: https://github.com/sveltejs/svelte-loader/issues/74#issuecomment-453949921

**Comment by josefaidt** [comment]
@ekhaled thanks for the link! Disabling `hotReload` in the svelte-loader options resolved the issue, interesting!
@pngwn is this okay to close now that we have a resolution?

**Comment by pngwn** [comment]
Sure thing.
