### ISSUE TITLE
How would you get a list of posts including metadata?

### ISSUE THREAD

**Issue by didier** [pngwn/MDsveX#158]
I want to get a list of all posts in my `/posts` directory as well as each post's metadata. However, I can't seem to find anywhere to point me in the right direction. i don't have a `.json` post index to map over, and I don't want to use one either. I should mention I previously got this working with [@jackfranklin/rollup-plugin-markdown](https://npmjs.org/package/rollup-plugin-markdown) using the following syntax: 
```js
import allPosts from './posts/*.md'
```

In short: when I create a new `md` file, I want that post to show up in a posts list

Essentially, I want
```md
/posts
  first-post.md
  second-post.md
```

to turn into something like this on the front-end
```md
My Blog

1. First Post
2. Second Post
```

**Comment by Pytal** [comment]
I'm currently using [import-all.macro](https://github.com/kentcdodds/import-all.macro) simply because the alternatives I've found are not as actively maintained but have also used [babel-plugin-import-glob-array](https://github.com/jescalan/babel-plugin-import-glob-array). Something like the snippet below would work.

```js
import importAll from 'import-all.macro'

export const posts = Object.entries(importAll.sync('./posts/*.svx'))
```
