### ISSUE TITLE
Code Highlighting is potentially broken

### ISSUE THREAD

**Issue by jamesb93** [pngwn/MDsveX#180]
Code highlighting for me is broken in what is mostly a default copy of this repo. None of the code blocks are highlighted. The only thing I have changed is the `code {}` css.

To diagnose the issue I made a dummy highlighter for the preprocesser.

```js
function highlighter (code, _lang) {
    console.log(code, _lang)
}
```

which causes the server and client both to crash stating:

`Cannot read property 'replace' of undefined`.

Im not too fussed about having PrismJS working - I would rather get something like [Shiki](https://shiki.matsu.io) working using a custom highlighter function, however Im not sure where to start debugging from here.

**Comment by pngwn** [comment]
That will cause the preprocessor to fail because passing in a custom highlighter function replaces the original and this does not return anything, highlighter functions must return a string.

In terms of highlighting not working, have you added the necessary CSS in order to style the output that Prism produces?

Shiki will be used in a future version but the same limitation will apply, it is down to you to add the CSS in order to actually style the output, mdsvex just generates the markup. This is currently poorly/un documented. [Relevant issue](https://github.com/pngwn/MDsveX/issues/63#issuecomment-633796271)
