### ISSUE TITLE
Escaping 'Curlywurlies' in text

### ISSUE THREAD

**Issue by theSherwood** [pngwn/MDsveX#19]
Using backticks to escape '{...}' changes the styling. Is there a way to use brackets in text so that they get the same styling as the rest of the paragraph?

**Comment by pngwn** [comment]
MDsveX doesn't escape curlywurlies intentionally so that end-users can use expressions in MDsveX just like they can in Svelte. Since this is a preprocessor (and now supports all Svelte template syntax) this isn't something I'm likely to change.

The solution is to do the same as you would in a Svelte component.

Using HTML entities:

`&#123;`: `{`
`&#125;`: `}`

Or:

`{ '{' + '}' }`

In principle, I could add a flag to escape these characters but then I would need to do some more comprehensive parsing to escape certain curlywurlies and not others, which I don't think is worth the tradeoff as it is a seldom used character. The manual approach should be fine for those times when such a character *is* needed in your template.

**Comment by code-IM-perfect** [comment]
@pngwn Both of these are not working for me
