### ISSUE TITLE
how do i bring my own components?

### ISSUE THREAD

**Issue by sw-yx** [pngwn/MDsveX#21]
in  MDX theres a concept of a provider where for example you can supply your own `<img>` and `<pre>` and so on components. as far as i can tell the only similar concept here is custom Layout?

**Comment by pngwn** [comment]
Oh, that's neat, I didn't know about that feature. 

This is pretty annoying to do right now in mdsvex (although possible) but would very straightforward if there was an AST to play with. I'll have a think but it just makes me more inclined to implement #20.

**Comment by pngwn** [comment]
@sw-yx I'm just thinking about the best way to do this, there are a few options.

- Magic globals - this could work in a few ways but is just not something I've ever likely to go for.
- Via front-matter - with a 'reserved' key name, this doesn't seem the best solution either but might be doable.
- A special `mdsvex` component similar to how `<svelte:options >` works. This makes sense in a few ways but does introduce a non-standard svelte tag.

The special component would look like this:
```svelte
<script>
  import { H1, H2, SpecialList, SpecialListItem  } from './customComponents';
</script>

<!-- Not sure what the actual name of the component should be yet --> 
<!-- 'components' is just an object of kv pairs, the key being the element name to be replaced --> 
<mdsvex:options components={{ H1, H2, ul: SpecialList, li: SpecialListItem }}>

# hello

- I
- am
- a
- list
```

Of course, this could be written however the user wants. 

```svelte
<script>
  import * as components from './customComponents';
</script>

<mdsvex:options components={components}>

# hello

- I
- am
- a
- list
```

In the following example, the user would need to ensure that the exports were named to match an HTML element but this should work. It means some extra work on my part as I'd need to actually find this object wherever it may be, so maybe it is a terrible idea from that perspective but I feel like it might give the best experience without resorting to globals (which I think should be minimised: what you save in not importing things you lose in comprehension at a later time). This also allows the flexibility of not tying your custom component names to the elements they will replace since it is just an object.

But it does introduce a new 'special' tag, which *is* a global essentially or at least an 'extension' to the language or a macro.

I'd be interested to know your thoughts.

**Comment by sw-yx** [comment]
yeah all this is in the right train of thought. i wanna explore "Magic globals" more 😅

> what you save in not importing things you lose in comprehension at a later time

so for this particular problem, i dont think magic is an issue -at all-. because our fallback is standard html h1/ul/li elements. so what i was thinking that we could put it in a store somewhere higher up the tree, and if it's there, use it, if not, fall back to regular html. whats the issue here?

99% sure you already saw it but just in case here's the provider idea for reference: https://mdxjs.com/getting-started#mdxprovider

**Comment by pngwn** [comment]
The issue with magic globals is that I generally don't like 'plugins' or extensions to tools with their own languages or sets of globals to introduce yet more. This just adds confusion and make an API harder to learn, not to mention harder to maintain in the future. 

```js
  import { One, Two, Three } from './Whatever'
```

Has a very standard meaning in Svelte and in the wider JS ecosystem. Suddenly rewriting those semantics to save on one line of code seems like a poor trade-off. There is a good chance that someone coming to an mdsvex file won't know about the global rules so wouldn't know why their components are being rendered with strange components instead of plain HTML tags. Having an explicit API for it is a hint that something else is happening that will require some reading of the documentation. Compare seeing an `H1` named import to seeing an explicit function call or special component tag that receives this component. Making custom components 'global' also makes the name of the imported component part the API which isn't awful but leaves me a little cold.  I may be overthinking this but I think one aspect of good API design is to follow the path of least surprise, which is why I have a general aversion to globals. 

As for a store higher up the tree, or using the tree at all: `mdsvex` is a preprocessor that works component by component. Even the Svelte compiler just works component by component. Everything `mdsvex` does it does at compile-time, there essentially *is* no tree until the code runs (at least in practical terms) at which point `mdsvex` can't do anything because it adds no additional runtime (at least for the time being). So all of this needs to be resolved at compile-time directly in the preprocessor.

MDX can do its provider thing because it is a runtime library, one of the advantages of `mdsvex` is that you just end up with plain Svelte components, there is no cost to using it essentially. What is needed is essentially a 'compiler flag' to let `mdsvex` know which settings to use when pre-compiling the `mdsvex` file.

---

I still don't have a strong opinion on any of this, I'm not implementing it right now anyway so I'll do some more research / thinking and see if there are any other elegant alternatives. 

There is also the possibility of allowing 'default' custom components, passed into the preprocessor options and allowing these to be overridden in each individual component as needed, which is somewhere in between magic globals and explicit. This is basically how custom layouts work. This *also* raises the option of whether custom layouts should have a new API instead of being passed via YAML front-matter.

**Comment by sw-yx** [comment]
yeah ok. i think youve convinced me that we shouldnt rely on a provider.

what i was trying to go for is portability, which is being able to bring in a bunch of markdown files and getting productive right away, instead of having to copy and paste the same boilerplate at the top of each one.

i think for is portability usecase, allowing default custom components like you do layouts, would be very nice.

**Comment by colinbate** [comment]
I’ve also been thinking about this recently, less in the context of bringing custom HTML tags (although that is interesting), but rather having a way to register a set of default components. I was originally thinking about it similar to how layouts work, except you’d specify a file that is prepended to each markdown file. Now that I think some more on it, you could even have it so that a different file was prepended based on some value in the front matter like a `types` field or something.

The use case I was imagining was when you have some common components that you want your content creators to be able to access, but they aren’t particularly comfortable with JS, but are comfortable with markdown and a bit of HTML.

**Comment by pngwn** [comment]
This probably isn't something I'd want to put in mdsvex itself but should be the responsibility of some higher-level tooling. This could probably be done by injecting some imports into mdsvex files inside a svelte preprocessor that only acts on mdsvex files.

**Comment by mjgartendev** [comment]
I think this may be a helpful reference: [svelte-portable-text](https://github.com/movingbrands/svelte-portable-text). 

The implementation isn't very useful in this scenario, but the abstract concept is an interesting consideration. It's for [Sanity's](https://www.sanity.io/) [block content spec](https://github.com/portabletext/portabletext), which works more along the lines of remark/unist (serialize -> AST -> deserialize ) but definitely doesn't map directly.

Essentially it exposes a `<Content/>` component that let's you pass in custom components as a prop for rendering it's children (an array of content blocks), and falls back to a set of default components for anything not user specified. If it doesn't find a matching component to render a content object it just passes it through unmodified.

In the example below, `content` would be a string of JSON representing Sanity's rich text spec, which I believe is _somewhat_ similar to a remark AST. And `<BlockContent/>` could be something mdsvex specific or whatever.
```svelte
<script>
  import BlockContent from "@movingbrands/svelte-portable-text";
  
  import Image from "./Image";
  import Link from "./Link";

  export let content;
  export const customSerializers = {
    types: {
      image: props => {
        return {
          component: Image,
          childNodes: props.children,
          props: {
            url: props.node.url
          }
        };
      }
    },
    marks: {
      link: props => {
        return {
          component: Link,
          childNodes: props.children,
          props: props.mark
        };
      }
    }
  };
  </script>

  <BlockContent blocks={content} serializers={customSerializers} />
```

I think if you used this idea within custom layouts you could create a type of modular preset system, where you can compose preset packages and use as needed by just specifying the relevant layout. Which would make up for the verbose initial configuration. Or don't use it and just get the default mdsvex behavior.

For reference, the [transformed mdxhast](https://astexplorer.net) seems to do something along these lines:
```jsx
...
const MDXLayout = "wrapper";
export default function MDXContent({ components, ...props }) {
  return (
    <MDXLayout
      {...layoutProps}
      {...props}
      components={components}
      mdxType="MDXLayout"
    >
...
```

There's a good chance this isn't feasible or even desirable, and I don't know if this makes since to be included in mdsvex, but after playing with this concept a bit it seemed like a decent solution so I thought I'd pass it along.

**Comment by pngwn** [comment]
> how do i bring my own components?

You install version 0.8.

**Comment by hermanbanken** [comment]
So how was this resolved? Nowhere in the docs do I see some way mentioned to provide some own components unless it is imported. I'd really like to avoid that technical syntax for my content editors. They do understand `<Youtube id="" />` but having to import those components (how'd they know where from?) doesn't make sense. I just want to provide some defaults.

(Context: trying to use [mdsvex with Netlify CMS](https://github.com/buhrmi/sveltekit-netlify-cms))

**Comment by Amerlander** [comment]
@hermanbanken did you found a workaround?
I think about using a Div-component and pass props in to decide whether it stays a div or should be handled as a different component.
