### ISSUE TITLE
Unexpected text added in pre tags when using compiler function

### ISSUE THREAD

**Issue by biah** [pngwn/MDsveX#283]
At first, I was using the `mdsvex` function to convert all my `.svx` files to markdown but later I decided to change it.
It wanted to access the converted contents through an API so I decided to use the `compile` function inside of my `blog/[svelte].json.js` file. Everything works alright but when it returns the html contents, it always inserts `{ @html }` around the pre tags.
![Capture](https://user-images.githubusercontent.com/63173187/126039929-8f6eb3b5-8093-4703-ba9b-c6d9a0fea63a.JPG)

**Comment by pngwn** [comment]
This is an optimisation that mdsvex performs, if you want to disable it then it will currently require a custom highlight function as described [in the docs](https://mdsvex.com/docs#highlight).

**Comment by RomainLanz** [comment]
Hello @pngwn! 👋🏻 

I have hard time understanding why adding `{@html ... }` to the computed HTML an optimization?

We already need to encapsulate the returns of the API to display the content as HTML in Svelte.

i.e:
```svelte
<script context="module">
  /**
   * @type {import('@sveltejs/kit').Load}
   */
  export async function load({ page, fetch }) {
    const response = await fetch(`/posts/${page.params.slug}.json`);

    if (response.ok) {
      const post = await response.json();

      return {
        props: { post }
      };
    }
}
</script>

<script>
  export let post = {};
</script>

<h1>{post.data.fm.title}</h1>

{@html post.code}
```

Therefore, adding `{@html ... }` seems wrong to me.

**Comment by pngwn** [comment]
This is only true if you are using the transformed mdsvex document as pure html that is inserted into the document. This isn't always the case (and will actually break a lot of what mdsvex offers).

At its core, mdsvex is a Svelte preprocessor. Meaning it takes an mdsvex file and produces a Svelte component, not HTML. The above only works because Svelte is so similar to HTML and you aren't using any dynamic features.

When using mdsvex is the recommended manner, the following:

```markdown
<script>
  import Comp from './Comp.svelte';
</script>

# hello

hello friends

<Comp />
```

Will produce:

```svelte
<script>
  import Comp from './Comp.svelte';
</script>

<h1>hello</h1>

<p>hello friends</p>

<Comp />
```

In the context of svelte this is a component. So ensuring large blocks of static HTML are optimised by Svelte is very important.
