### ISSUE TITLE
rehype-pretty-code for docs?

### ISSUE THREAD

**Issue by janosh** [pngwn/MDsveX#388]
[`rehype-pretty-code`](https://github.com/atomiks/rehype-pretty-code) [[docs]](https://rehype-pretty-code.netlify.app/) looks cool. Could be considered as an alternative to Prism for syntax highlighting the MDsveX docs.

https://github.com/pngwn/MDsveX/blob/cb0d0d00c00008fbf37698a08ededd05fbe9a413/packages/site/rollup.config.js#L1-L4

**Comment by jokull** [comment]
Yeah it looks awesome. Have you tried it with Svelte?

**Comment by pngwn** [comment]
Looks cool but I doubt I'll change anything fundamental until I rebuild the docs for the next major version. I'll also be using whatever mdsvex's default highlighter is. In the past I've said that will be shiki (the highlighter used by `rehype-pretty-code`) but that may not be the case now. Either way it will sue the same approach (piggy-backing off the vscode/ textmate ecosystem, because that was a genius move).

**Comment by Namaskar-1F64F** [comment]
Came back here after trying to find https://rehype-pretty-code.netlify.app/ for ever. Never seen anything like it before with its context-aware syntax.

I think it's a killer feature for a blog-style code explanation approach. 

Also thanks for all the work on mdsvex. I love using it.
