### ISSUE TITLE
Each blocks *do* work

### ISSUE THREAD

**Issue by louwers** [pngwn/MDsveX#41]
The 'Try it' page contains the following phrase:

> You can't use `each` blocks. Don't try, it wont work.

Of course I tried it. They do in fact work...
Try this:

`````
```js exec
	let cats = [
		{ id: 'J---aiyznGQ', name: 'Keyboard Cat' },
		{ id: 'z_AbfPXTKms', name: 'Maru' },
		{ id: 'OUtn3pvWmpg', name: 'Henri The Existential Cat' }
	];
```
<ul>
	{#each cats as cat}
		<li><a target="_blank" href="https://www.youtube.com/watch?v={cat.id}">
			{cat.name}
		</a></li>
	{/each}
</ul>
`````

**Comment by pngwn** [comment]
You are absolutely right, they do work and they have done for some time now. I just haven’t updated the docs. 

This will all be updated shortly with the new version.

**Comment by sw-yx** [comment]
🔥

**Comment by heri16** [comment]
Do they work together with markdown syntax?

**Comment by pngwn** [comment]
This depends, I don't really recommend mixing them too much. mdsvex isn't really intended to be used as a new svelte-markdown-language, it just allows a mix in certain situations.

The rules of markdown are still observed (mostly), which means that newlines are significant. It also means that if you want to 'leave' markdown and enter HTML mode, you need to consider newlines if you want to 're-enter' markdown mode. In markdown the following does not generate an `h1` tag:

```markdown
<div>
# h1
</div>
```

You need to add a newline:

```markdown
<div>

# h1
</div>
```

Svelte syntax is similar. Something like this won't work because there is no new line:

```svelte
{#each cat as cats}
*{cat}*
{/each}
```

This does work, but wraps each cat in a new paragraph:

```svelte
{#each cat as cats}

*{cat}*

{/each}
```

The difficulty in supporting this kind of syntax is that it makes it tricky to work out what a user actually wants (sometimes we might want no wrapping, sometimes paragraph wrappers, sometimes `li` should wrap the text but all `li`s should only have a single `ul` wrapper) and I don't particularly want to implement a completely custom markdown/svelte variant. Because markdown is newline sensitive but svelte isn't, I don't want to complicate things by supporting strange variants.  You can *technically* use markdown in each blocks, assuming you observe the normal markdown rules, however, in all but the simplest of cases, the results probably won't be what you are after.

Most things should mix relatively well together but `each` blocks are one of the exceptions to that as this is a simple transformer as opposed a custom language in and of itself. Block-level markdown should be fine, inline markdown will be more difficult to use in side the `each`. 

I would recommend putting most of your logic inside layouts and embedded components, and keeping your mdsvex files relatively straightforward.

**Comment by pngwn** [comment]
mdsvex is now a superset of svelte.

**Comment by heri16** [comment]
Lot's of refactoring with unified.js

Will nested each now work?

**Comment by pngwn** [comment]
Nested `each` will work depending on line breaks, normal markdown rules are applied here. What did you mean specifically by 'nested each'.

I might need to try to throw some more helpful errors with `each` blocks specifically because the handling can be confusing.

**Comment by archiewood** [comment]
How would you propose going about using #each for `li` currently?

For example if I'm trying to generate a list of page links

1. Works
```
{#each all_orgs as org}
- [{org}](/{org}/)

{/each}
```
Problem: Then I get line breaks between my `ul` lists which is visually odd

2. Doesn't work 
```
{#each all_orgs as org}
- [{org}](/{org}/)
{/each}
```
Problem: Svelte chokes on the output: `

I guess I could:
```
<ul>
{#each all_orgs as org}
<li><a href={org}>{org}</a> </li>
{/each}
</ul>
```
But that feels like I'm losing a lot of the benefits of MDSveX at that point.

@pngwn What would be the layouts / embedded component approach you suggested here?
