### ISSUE TITLE
Use mdsvex as custom preprocessor in server route code

### ISSUE THREAD

**Issue by ekafyi** [pngwn/MDsveX#42]
Hi,

I would like to use SVX files with Sapper dynamic routing (eg. `routes/blog/[slug].svelte`, `routes/blog/[slug].json.js`). Wondering if it’s possible to use mdsvex the way [marked](https://github.com/markedjs/marked) is use in Svelte’s official site ([relevant code here](https://github.com/sveltejs/svelte/blob/master/site/src/routes/blog/_posts.js#L30-L50))?

Thanks!

**Comment by pngwn** [comment]
Yes, and no. Since mdsvex is a svelte preprocessor, it returns a svelte component so that server route would also need to compile the component and return the JS which would then need to be mounted to the document somewhere. You couldn't just insert the source with `{ @html content }` like you can with the parsed markdown in the docs as what you get back is not HTML at all. It *could*. be HTML if you didn't do anything special (no dynamic code, no layouts, etc.) but in that case, you could just use plain markdown.

I'll be looking at building more tooling and integrations for mdsvex as time allows. but I'm already way behind, so I can't make any promises or give any timescales right now.

**Comment by sw-yx** [comment]
i do like using "svx" as the file extension, what say you @pngwn

**Comment by pngwn** [comment]
Yeah. I guess `.svexy` will have to go at some point. `.svx` is probably my preferred alternative. Maybe I should change this default for 0.5.
