### ISSUE TITLE
ergonomic asset URL prefixing

### ISSUE THREAD

**Issue by 18kimn** [pngwn/MDsveX#457]
I'd like to setup my SvelteKit+mdsvex project like this:

```
src/routes
  - posts
    - my-first-post
       - index.md
       - figure.png
    - second-post-yay
    (and so on)
```

Inside `index.md`, it would be ergonomic to reference `figure.png` as follows:

```
![Some figure caption.](./figure.png)
```

The `./` prefix feels natural to me because `figure.png` is in the same directory as `index.md`. 

Ideally, this would result in a page `posts/my-first-post` and the reference to `figure.png` resulting in a request for the file at `posts/my-first-post/figure.png`. However, in SvelteKit[^1], the `./figure.png` URL is left in the document, and since the content in `index.md` shows up at `posts/my-first-post`, the reference to `figure.png` points to `posts/figure.png`, which is a nonexistent file. 

Could there be a way to make this work with mdsvex or sveltekit URL resolution that anyone knows of? Apologies if this is off-topic or in the wrong repo

[^1]: I'm guessing a similar issue could be present in other setups

**Comment by nosovk** [comment]
Yep, looks like you want to get something like that: https://github.com/MailCheck-co/mailcheck.site/tree/master/src/routes/blog/about-mailcheck-features

It's possible due to that hack: https://github.com/MailCheck-co/mailcheck.site/blob/master/mdsvexplugins/mdsvex-url-to-import.js

It was described in some older issue here, but it works like a charm for a last year.

**Comment by 18kimn** [comment]
Ah great, thank you!
