### ISSUE TITLE
Demo shows blank result

### ISSUE THREAD

**Issue by c0derabbit** [pngwn/MDsveX#57]
hey,

https://mdsvex.pngwn.io/ shows a blank result, its `<body>` seems to be empty. see screenshots below.

macOS Catalina 10.15.2, same empty result on Firefox 74.0, Brave 1.3.115 (Chromium 80.0......) and Safari

![image](https://user-images.githubusercontent.com/16685596/78508148-876dee00-777c-11ea-98cf-931d9202c363.png)

![image](https://user-images.githubusercontent.com/16685596/78508090-2e05bf00-777c-11ea-8cd3-c0e511bf10bf.png)

**Comment by pngwn** [comment]
Is broken. It shall soon be fixed.

**Comment by davehorner** [comment]
Here's the output of WIN10 -  chrome Version 80.0.3987.163 (Official Build) (64-bit)
Concerning I'm not sure where to start debugging an error like this; is it svelte or mdsvex issue.  The changes to fix it will be interesting to see.  Thank you @pngwn!

VM87 about:srcdoc:1 Uncaught SyntaxError: Invalid or unexpected token

(index):1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

b5dcc894-1dd1-4592-99aa-3d19f8e25fbe:1 Uncaught (in promise) null
(anonymous) @ b5dcc894-1dd1-4592-99aa-3d19f8e25fbe:1

**Comment by pngwn** [comment]
I have no idea what this was but it has been broken for a long time!

We have a new site now with a shiny new REPL: https://mdsvex.com

**Comment by c0derabbit** [comment]
sweet!

**Comment by davehorner** [comment]
that is really sweet it is working.  It is very nice;  and closes the ticket.  
how I would go about understanding the concern and steering clear of it?

How might one get "Uncaught SyntaxError: Invalid or unexpected token" - empty output - is a ledge to be aware of and makes me unsure of a language/tool/xyz that might find myself in such a predicament. blackbox debugging is no fun.

**Comment by pngwn** [comment]
That looks like a rollup parsing error, those message can be unhelpful. In this case I believe it was because nothing was being passed to rollup and it was choking. Ideally the tool that uses rollup should generate some useful messages. The plugin that rollup is calling will process the file before it touches rollup so you have space to handle such failures more elegantly. Svelte has a series of helpful error messages to avoid this (although they c9ould still be improved) and I have ann issue to improve the error handling on mdsvex #39
