### ISSUE TITLE
Indentation seems to break compiler

### ISSUE THREAD

**Issue by babycourageous** [pngwn/MDsveX#71]
It seems that indenting HTML code when writing .svx components breaks the compiler and makes it think that elements weren't closed.

Seems to happen when there are multiple levels of indentation with space and returns like: 

```
<main>
  <h1>Major Headline</h1>
    <section>

      <p>Here is text</p>
      <h2>A Second Heading</h2>
      
      <SvelteComponentToRender />

      ```html
      <h1>Example</h1>
      <p>code block</p>
      ```

    </section>
</main>
```

The error: 

```
[!] (plugin svelte) ParseError: <section> was left open
src/App.svx
12: <main>
13:   <h1>Major Headline</h1>
14:   <section>
      ^
15:     <p class="info">
16:       All found on
ParseError: <section> was left open
    at error (project_folder/node_modules/svelte/src/compiler/utils/error.ts:25:16)
    at Parser$1.error (project_folder/node_modules/svelte/src/compiler/parse/index.ts:93:3)
    at new Parser$1 (project_folder/node_modules/svelte/src/compiler/parse/index.ts:54:9)
    at parse (project_folder/node_modules/svelte/src/compiler/parse/index.ts:208:17)
    at compile (project_folder/node_modules/svelte/src/compiler/compile/index.ts:79:14)
    at project_folder/node_modules/rollup-plugin-svelte/index.js:252:22
    at ModuleLoader.addModuleSource (project_folder/node_modules/rollup/dist/shared/rollup.js:17430:30)
    at ModuleLoader.fetchModule (project_folder/node_modules/rollup/dist/shared/rollup.js:17491:9)
    at project_folder/node_modules/rollup/dist/shared/rollup.js:17461:36
    at async Promise.all (index 0)
```

I wasn't sure if this was a Markdown thing i wasn't aware of or if it is MDsvX related. 

If this is clear as mud I will try to get a better example for ya!

**Comment by pngwn** [comment]
Interesting. It seems to be the indented codeblocks. I'll take a look at this over the weekend.

**Comment by babycourageous** [comment]
Not a problem at all. Totally not an emergency, heheh. Congrats on the hot new release!

**Comment by pngwn** [comment]
Actually, on second glance, this isn't as straightforward as it seemed.

I could possible fix the error but this won't actually do what you might think. If the above code didn't error the above code block would actually look like this when rendered:

```html
      <h1>Example</h1>
      <p>code block</p>
```

Or perhaps this, if we trimmed leading whitespace:

```html
<h1>Example</h1>
      <p>code block</p>
```

This is because fenced code blocks are designed to respect the whitespace you give them, tracking the current indentation level seem like it could lead me down a dark and lonesome path. This behaviour is consistent with markdown and mdx, so I think it makes sense to stay consistent.

Indentation is a bit of an issue with markdown, even though I have disabled code blocks via indentation, there are still some quirks to markdown if you add whitespace before your markdown code.

I'll look a bit more closely into the above snippet and see what makes the most sense considering the above. It seem that the indentation of the closing  backticks are the culprit and I'm not too keen on transforming messing too much with the internal values of default markdown blocks. I'll see what I find.

**Comment by babycourageous** [comment]
Oh for sure - nothing to lose sleep over. Based on your findings and looking closer it's probably more Markdown related than MDsveX. I just de-indented everything and all is well. 

And indeed it was the code block causing the error to get thrown.

Just for the sake of having it - you can see that syntax highlighting shows that the Markdown file isn't a fan of indenting the same way you might with an HTML file: 

![image](https://user-images.githubusercontent.com/14936212/83363142-16eee200-a365-11ea-87ae-64a4f8169f81.png)

It's basically begging you to get rid of those indentations heheh.

Thanks @pngwn !

**Comment by pngwn** [comment]
I will expand on this in the limitations section of the docs, I don't consider this a bug indentation will cause issues with markdown as paer the standard.

**Comment by babycourageous** [comment]
Totally agree. 

Heck, I wouldn't indent in traditional markdown so it makes perfect sense that would be the case here as well!

Thanks for looking into it !

**Comment by pngwn** [comment]
Apprenty I decided to not bother with any punctuation. Amazed you could even decipher that.

**Comment by babycourageous** [comment]
![image](https://user-images.githubusercontent.com/14936212/84709842-f1e79b00-af30-11ea-8208-27f5e5b40113.png)
