### ISSUE TITLE
Code block formatting does not always respect spacing/returns

### ISSUE THREAD

**Issue by babycourageous** [pngwn/MDsveX#72]
For some reason code blocks aren't respecting the hard return. 

In `.svx` file: 

```
```html
<style>
  .red {
    color: red;
  }
</style>
```

Output: 

<img width="471" alt="Screen Shot 2020-05-30 at 12 49 08 PM" src="https://user-images.githubusercontent.com/14936212/83334352-f85cee00-a273-11ea-95ed-88cb134e2133.png">

Just wanted to bring it to your attention just in case it is relevant for ya.

Thanks!

**Comment by pngwn** [comment]
I’m pretty sure this a svelte bug but I’ll double check.

**Comment by babycourageous** [comment]
Makes sense - I seem to recall running into this with another svelte/markdown type package. Just can't remember which or when for reference.

Loving the new update!

**Comment by BillyLevin** [comment]
MDsveX does seem to be returning the correct html string (I copy and pasted it into my site and the indentation was correct) so that would point to it being a svelte problem

Pretty annoying bug since most blog posts about svelte are gonna have code snippets starting with either a `<script>` or `<style>` tag

Haven't been able to track down what's causing this yet but if I do I'll make an issue for it over there

Also is it significant that the svelte docs don't have this problem? I know they don't use MDSveX, but they do use Sapper and Prism

**Comment by pngwn** [comment]
This is specifically a problem with svelte generating the html and they way it handles the whitespace, I forget the specifics but I'll dig deeper shortly. 

The Svelte site doesn't have this issue because it renders the docs via `{@html source}` which essentially bypasses svelte's HTML generation and just dumps the raw HTML into the document. I do have a really hacky way to fix this with some string replacement, I might add that to mdsvex's syntax highlighting until this is fixed. I'll have to think about whether or not removing it will cause any problems in the future.

**Comment by pngwn** [comment]
fixed in #81

**Comment by babycourageous** [comment]
Awesome!
Thanks @pngwn and @dominikg
